import requests
import json

VIDEO_ID = "Hu4Yvq-g7_Y"
# Reliable Piped instances
INSTANCES = [
    "https://pipedapi.kavin.rocks",
    "https://api.piped.privacy.com.de",
    "https://pipedapi.tokhmi.xyz",
    "https://pipedapi.adminforge.de",
    "https://pipedapi.drgns.space",
    "https://api.piped.sf0.moe",
    "https://pipedapi.smnz.de",
    "https://api-piped.mha.fi"
]

def test_piped():
    for base_url in INSTANCES:
        print(f"Testing Piped Instance: {base_url}")
        try:
            url = f"{base_url}/streams/{VIDEO_ID}"
            resp = requests.get(url, timeout=10)
            if resp.status_code != 200:
                print(f"Failed: {resp.status_code}")
                continue
            
            data = resp.json()
            subtitles = data.get("subtitles", [])
            print(f"Found {len(subtitles)} subtitles.")
            
            # Find English
            en_sub = next((s for s in subtitles if s["code"] == "en"), None)
            if not en_sub:
                 # Try auto-generated
                 en_sub = next((s for s in subtitles if s["code"] == "en" and s.get("autoGenerated")), None)

            if en_sub:
                print(f"Found English sub: {en_sub['url']}")
                # Fetch text content (it's usually VTT or JSON)
                sub_resp = requests.get(en_sub['url'])
                if sub_resp.status_code == 200:
                    print("SUCCESS! Got subtitle content.")
                    print(sub_resp.text[:200])
                    return
            else:
                print("No English subtitles found.")
                
        except Exception as e:
            print(f"Error: {e}")

test_piped()
